In [1]:
import numpy as np

In [2]:
a = np.zeros(5) #0으로 채워진 배열

In [3]:
print(a)

[0. 0. 0. 0. 0.]


In [4]:
a

array([0., 0., 0., 0., 0.])

In [6]:
type(a)

numpy.ndarray

In [7]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [8]:
a.min() #a의 최솟값

0.0

In [9]:
a.max() #a의 최댓값

0.0

In [10]:
a = np.array([1, 2, 3, 4, 5])

In [11]:
print(a)

[1 2 3 4 5]


In [12]:
type(a)

numpy.ndarray

In [13]:
a.max()

5

In [14]:
a.min()

1

In [15]:
a = np.array([[1,2,3],[4,5,6]]) #이차원 배열

In [16]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
b = [1, 'abc', True]

In [18]:
b

[1, 'abc', True]

In [19]:
type(b[0])

int

In [20]:
type(b[1])

str

In [21]:
type(b[2]) #다른 타입으로 가능하다

bool

In [22]:
a = np.array(b)

In [24]:
print(a) #전부 문자열 타입이 됨(b랑 다름)

['1' 'abc' 'True']


In [25]:
type(a[0]) #넘파이의 문자열이 된다(넘파이는 같은 타입으로만 배열이 된다)

numpy.str_

In [26]:
a = np.zeros((3,2))

In [27]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [28]:
a = np.zeros((3,2,4))

In [29]:
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [30]:
a = np.eye(5)

In [31]:
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
a = np.eye(5, k =1) #1을 한칸씩 올림

In [33]:
a

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [34]:
a = np.eye(5, k = -2) #1을 두칸씩 내림

In [36]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [37]:
a = np.identity(3) #중간에만

In [38]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
a = np.ones(10) #1이 차있는 배열

In [40]:
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [41]:
a = np.ones((3,4))

In [42]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
a * 5 #구성요소들에 5곱한것이 된다

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [44]:
b= [1,1,1]

In [45]:
b*5 #파이썬 리스트에서 *하면 그 리스트를 반복하는게 된다

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [46]:
a = np.full((3,4), 123) #3,4모양의 123이 채워진 배열

In [47]:
a

array([[123, 123, 123, 123],
       [123, 123, 123, 123],
       [123, 123, 123, 123]])

In [52]:
a = np.empty((5,6)) #초기화 안되서 메모리에 있던값 그냥 출력됨

In [53]:
a

array([[7.44655570e-312, 7.44644704e-312, 0.00000000e+000,
        0.00000000e+000, 7.42698527e-312, 5.02034658e+175],
       [6.49442829e+169, 1.77272945e-051, 1.34657427e+165,
        4.08869641e-037, 2.59027864e-144, 3.80985069e+180],
       [1.14428494e+243, 2.59027907e-144, 7.79952704e-143,
        2.72727378e-056, 3.72472305e-057, 4.50720643e+174],
       [1.04833321e+165, 4.99874559e+217, 5.49419094e-143,
        2.91237123e+257, 5.56111702e+180, 5.74015544e+180],
       [1.94919988e-153, 2.59027858e-144, 2.59903818e-144,
        5.58047018e-091, 5.35653039e-038, 3.31485640e-033]])

In [54]:
a = np.full((5,6) , 7)

In [55]:
a

array([[7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7]])

In [56]:
b = np.ones_like(a) #a와 같은 배열을 만들고 1을 채움

In [57]:
b

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [58]:
b = np.zeros_like(a)

In [59]:
b

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [60]:
b = np.full_like(a, 100)

In [61]:
b

array([[100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100]])

In [62]:
a*b #a는 7이 전부 저장되어있고 b는 전부 100이 저장되어있어 둘이 곱한 700이 전부 채워짐

array([[700, 700, 700, 700, 700, 700],
       [700, 700, 700, 700, 700, 700],
       [700, 700, 700, 700, 700, 700],
       [700, 700, 700, 700, 700, 700],
       [700, 700, 700, 700, 700, 700]])