In [1]:
import numpy as np

In [2]:
a = np.linspace(0 , 100) #shift + tab누르면 함수 설명 볼 수 있다

In [3]:
a

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [4]:
a = np.linspace(0, 100, 9)

In [5]:
a

array([  0. ,  12.5,  25. ,  37.5,  50. ,  62.5,  75. ,  87.5, 100. ])

In [6]:
a = np.linspace(0,100,9,endpoint = False)

In [7]:
a

array([ 0.        , 11.11111111, 22.22222222, 33.33333333, 44.44444444,
       55.55555556, 66.66666667, 77.77777778, 88.88888889])

In [8]:
a = np.linspace(0,100,5)

In [9]:
a

array([  0.,  25.,  50.,  75., 100.])

In [10]:
a = np.logspace(0,100,10)

In [11]:
a

array([1.00000000e+000, 1.29154967e+011, 1.66810054e+022, 2.15443469e+033,
       2.78255940e+044, 3.59381366e+055, 4.64158883e+066, 5.99484250e+077,
       7.74263683e+088, 1.00000000e+100])

In [12]:
a = np.ones(5)

In [13]:
a

array([1., 1., 1., 1., 1.])

In [14]:
a.dtype

dtype('float64')

In [15]:
a= np.ones(5, dtype = np.int8)

In [16]:
a

array([1, 1, 1, 1, 1], dtype=int8)

In [17]:
a.dtype

dtype('int8')

In [18]:
a.shape #배열 형태

(5,)

In [19]:
a.ndim #몇차원인지

1

In [22]:
a = np.ones((3,4), dtype = np.int32)

In [24]:
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [25]:
a.shape

(3, 4)

In [26]:
a.ndim

2

In [27]:
a = np.ones((2,3,3,4))

In [28]:
a

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [29]:
a.shape

(2, 3, 3, 4)

In [30]:
a.ndim

4

In [31]:
a.size #원소갯수

72

In [32]:
a.itemsize #원소의 바이트 크기

8

In [33]:
a = np.ones(5,dtype=np.int8)

In [34]:
a.size

5

In [35]:
a.itemsize

1

In [36]:
range(5,10)

range(5, 10)

In [37]:
list(range(5,10))

[5, 6, 7, 8, 9]

In [38]:
list(range(5,10,2))

[5, 7, 9]

In [39]:
list(range(5,10,0.1)) #range에는 정수만 가능

TypeError: 'float' object cannot be interpreted as an integer

In [40]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [41]:
np.arange(5,10,0.1) #넘파이에서 arange는 실수 가능

array([5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2,
       6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5,
       7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8,
       8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [42]:
np.sum([1,2,3]) #합을 구한다

6

In [43]:
np.sum(range(100)) #0~99까지 합

4950

In [44]:
%time np.sum(range(100)) #시간구하기

Wall time: 0 ns


4950

In [108]:
%time np.sum( np.arange(1000000)) #더빠름 (10만부터 계산 결과가 이상하게나온다. )

Wall time: 4.99 ms


1783293664

In [107]:
%time sum( range(1000000))

Wall time: 62.8 ms


499999500000

In [123]:
a = np.arange(1000000)

In [126]:
b = range(1000000)

In [124]:
a

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [127]:
b

range(0, 1000000)

In [128]:
np.sum(a)

1783293664

In [130]:
sum(b)

499999500000