In [3]:
import numpy as np

### 객체...(object)
모든것이 다 객체이다
2가지 유형
1. mutable 객체 : 수정이 가능 ex)list, dict, set
2. immutable 객체 : 수정이 불가능 ex) tuple, int, float, string

In [30]:
a = [1,2]

In [29]:
id(a)

1973878352208

In [31]:
a[0] = 100 #객체내용 수정가능-mutable

In [32]:
a

[100, 2]

In [13]:
id(a) #리스트 변수 변경해도 id는 그대로

1973878352208

In [33]:
a= 1

In [34]:
id(a)

1973878352176

In [37]:
id(1) #a하고 1같음

1973878352176

In [38]:
a = 2

In [39]:
a

2

In [40]:
id(a) #int는 id가 변경 -> 객체가 달라짐

1973878352208

In [41]:
id(2) #2와 같아짐

1973878352208

In [42]:
# -5 ~ 256까지 정수는 객체로 있음
a = 257

In [43]:
id(a)

1973980148048

In [44]:
id(257) #257부터는 객체가 달라짐

1973980149904

In [45]:
a = 258

In [46]:
id(a)

1973980150032

In [47]:
a = [1,2]

In [48]:
b = a #a와 b가 같은 객체가 된다. shallow copy(얕은 복사)

In [49]:
a

[1, 2]

In [50]:
b

[1, 2]

In [51]:
b[0] = 100

In [52]:
b

[100, 2]

In [53]:
a #b변경해도 a같이 변경

[100, 2]

In [54]:
id(a)

1973980323264

In [55]:
id(b) #같다

1973980323264

In [56]:
b = a.copy() #deep copy(깊은 복사)

In [57]:
a

[100, 2]

In [58]:
b

[100, 2]

In [59]:
id(a)

1973980323264

In [60]:
id(b) #a와 b가 다르다

1973980332736

In [61]:
b[0] = 2000

In [62]:
b

[2000, 2]

In [63]:
a

[100, 2]

In [64]:
a = [[1,2,3]] #이차원 배열

In [65]:
a

[[1, 2, 3]]

In [66]:
b = a.copy()

In [67]:
b

[[1, 2, 3]]

In [68]:
b[0][0] = 2000

In [69]:
a #a값도 바뀜(a의 id와 b의 id는 다르지만 a[0]이랑 b[0]이랑은 같음)

[[2000, 2, 3]]

In [70]:
id(a[0])

1973980273664

In [71]:
id(b[0])

1973980273664

In [72]:
import copy #진짜 deepcopy를 쓰기위해서는 copy.deepcopy를 써야된다.

In [77]:
a = [[1,2,3]]

In [78]:
b = copy.deepcopy(a)

In [79]:
b[0][0] = 3000

In [80]:
b

[[3000, 2, 3]]

In [81]:
a

[[1, 2, 3]]

In [82]:
a =b =np.array([1,2,3])

In [83]:
a

array([1, 2, 3])

In [84]:
b

array([1, 2, 3])

In [85]:
b[0] = 1000

In [86]:
b

array([1000,    2,    3])

In [87]:
a

array([1000,    2,    3])

### ndarray도 mutable type!!

In [88]:
a[1:]

array([2, 3])

In [89]:
a

array([1000,    2,    3])

In [90]:
c = a[1:] #view

In [91]:
c

array([2, 3])

In [92]:
c[0] = 2000

In [93]:
c

array([2000,    3])

In [94]:
a

array([1000, 2000,    3])

In [95]:
a = [[1,2,3],[4,5,6]]

In [96]:
a

[[1, 2, 3], [4, 5, 6]]

In [97]:
a[0][2]

3

In [98]:
a[1][1]

5

In [99]:
a[1,1] #안됨

TypeError: list indices must be integers or slices, not tuple

In [100]:
b = np.array(a) #넘파이로 깊은 복사가 됨

In [101]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
a[0] = 1000

In [103]:
a

[1000, [4, 5, 6]]

In [104]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
b[0][0]

1

In [106]:
b[1][1]

5

In [107]:
b[1,1] #된다

5