### 불리언 인덱싱

In [5]:
import numpy as np

In [6]:
a = np.arange(10)

In [7]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a[0]

0

In [9]:
a[1]

1

In [10]:
a = np.arange(2)

In [11]:
a

array([0, 1])

In [13]:
a[[True, False]]

array([0])

In [15]:
a = np.array([6,1,4,7,9,3])

In [16]:
a

array([6, 1, 4, 7, 9, 3])

In [17]:
a>5

array([ True, False, False,  True,  True, False])

In [18]:
a[a>5]

array([6, 7, 9])

In [19]:
a = np.array([[3,5,7,1,2],[6,1,2,8,9]])

In [20]:
a[a>5]

array([7, 6, 8, 9])

In [21]:
a

array([[3, 5, 7, 1, 2],
       [6, 1, 2, 8, 9]])

In [22]:
a%2 == 1

array([[ True,  True,  True,  True, False],
       [False,  True, False, False,  True]])

In [23]:
a[a%2==1]

array([3, 5, 7, 1, 1, 9])

In [24]:
a[a%2 == 0]

array([2, 6, 2, 8])

In [25]:
a = np.arange(2)

In [26]:
a[[True, True]]

array([0, 1])

In [27]:
a[[True,True, True]]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 3

In [28]:
a = np.arange(0,20)

In [29]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [30]:
a.shape

(20,)

In [31]:
a.ndim

1

In [32]:
a.reshape((2,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [33]:
a.reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [34]:
b = a.reshape(5, 4)

In [35]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [39]:
b[0][0] = 1000

In [40]:
b

array([[1000,    1,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11],
       [  12,   13,   14,   15],
       [  16,   17,   18,   19]])

In [41]:
a #얕은 복사이다.

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19])

In [42]:
a.reshape((3,9)) #20개를 3*9로는 불가능

ValueError: cannot reshape array of size 20 into shape (3,9)

In [43]:
a.reshape((2.5)) #마찬가지로 작은것도 불가능

TypeError: 'float' object cannot be interpreted as an integer

In [44]:
b = np.arange(100).reshape((20,5)) #생성하면서 형태 바로 변경

In [46]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

### Fancy Indexing

In [47]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [49]:
b[0,0]

0

In [50]:
b[10,4]

54

In [51]:
b[[0, 2, 5]] #지정한 행만으로 리스트

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [52]:
b[[0,2,5], [1,3,1]] #열까지도 지정 가능(0번행의 1번열, 2번행의 3번열, 5번행의 1번열)

array([ 1, 13, 26])

In [54]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [55]:
b[[3]] #행을 가져오지만 같은 차원으로 가지고옴 현재 2차원이라서 2차원

array([[15, 16, 17, 18, 19]])

In [56]:
b[3,:] #행을 1차원으로 가지고옴

array([15, 16, 17, 18, 19])

In [57]:
c = b[[3, 4]]

In [58]:
c

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [59]:
c.ndim

2

In [60]:
d = b[3:5,:] #두개하면 2차원

In [61]:
d

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [63]:
d = b[3,:] #한개 하면 1차원

In [64]:
d

array([15, 16, 17, 18, 19])

In [65]:
d.ndim

1