In [1]:
import numpy as np

### 벡터화 연산 (Vectorize Operation)
elementwise 연산

In [2]:
a = np.arange(20).reshape((4,-1))

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
b = np.arange(100,120).reshape((4,-1))

In [5]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [8]:
b

array([[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119]])

In [9]:
a + b

array([[100, 102, 104, 106, 108],
       [110, 112, 114, 116, 118],
       [120, 122, 124, 126, 128],
       [130, 132, 134, 136, 138]])

In [10]:
a * b

array([[   0,  101,  204,  309,  416],
       [ 525,  636,  749,  864,  981],
       [1100, 1221, 1344, 1469, 1596],
       [1725, 1856, 1989, 2124, 2261]])

In [11]:
a @ b # matrix dot operation , 행렬곱() 앞의 열과 뒤의 행의 갯수가 같아야함.

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 5)

In [12]:
b.T #전치행렬

array([[100, 105, 110, 115],
       [101, 106, 111, 116],
       [102, 107, 112, 117],
       [103, 108, 113, 118],
       [104, 109, 114, 119]])

In [13]:
a @ b.T

array([[1030, 1080, 1130, 1180],
       [3580, 3755, 3930, 4105],
       [6130, 6430, 6730, 7030],
       [8680, 9105, 9530, 9955]])

In [14]:
c = np.matrix(a)

In [15]:
c

matrix([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [16]:
c  = np.matrix([[1,2], [3,4]])

In [17]:
c

matrix([[1, 2],
        [3, 4]])

In [18]:
c * c

matrix([[ 7, 10],
        [15, 22]])

### Broadcasting

In [19]:
[1,2,3] + 10 #불가능 리스트는 리스트끼리

TypeError: can only concatenate list (not "int") to list

In [20]:
[1,2,3] + [10]

[1, 2, 3, 10]

In [21]:
a = np.arange(5)

In [22]:
a

array([0, 1, 2, 3, 4])

In [23]:
a + 10 #가능 벡터화 연산으로 10이 [10,10,10,10,10] 브로드캐스팅됨

array([10, 11, 12, 13, 14])

In [24]:
a = np.arange(6).reshape(3,-1)

In [25]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [26]:
a + 10

array([[10, 11],
       [12, 13],
       [14, 15]])

In [27]:
b = np.array([20,30])

In [28]:
a + b #이것도 브로드캐스팅되어 [20,30],[20,30],[20,30]이 되어 계산된다

array([[20, 31],
       [22, 33],
       [24, 35]])

In [29]:
a = np.arange(9).reshape((3,3))

In [30]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
a + b #이 경우 브로드캐스팅은 배수로 늘어남으로 모양을 맞추지 못하여 불가능

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [32]:
a = np.arange(12).reshape((3,4))

In [33]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
a + b

ValueError: operands could not be broadcast together with shapes (3,4) (2,) 

In [35]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
np.sum(a)

66

In [37]:
np.max(a)

11

In [38]:
np.min(a)

0

In [39]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
np.sum(a, axis = 0) #축 방향으로 더하기. 0은 밑으로

array([12, 15, 18, 21])

In [42]:
np.sum(a, axis = 1) #1은 옆으로

array([ 6, 22, 38])

In [43]:
np.max(a, axis = 0) #max도 가능

array([ 8,  9, 10, 11])

In [44]:
np.max(a, axis = 1)

array([ 3,  7, 11])

In [45]:
np.min(a, axis = 0) #min도 가능

array([0, 1, 2, 3])

In [46]:
np.min(a, axis = 1)

array([0, 4, 8])

In [47]:
type(np.max)

function

In [48]:
type(np.add)

numpy.ufunc

### Universial Function

ndarray 데이터에 원소별로 연산을 수행하는 함수들

In [49]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
np.add(a, 100)

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111]])

In [51]:
a + 100

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111]])

In [52]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
np.max(a)

11

In [54]:
np.argmax(a) #최댓값의 위치 알려줌

11

In [55]:
np.argmin(a) #최솟값의 위치 알려줌

0

In [56]:
a = np.arange(30)

In [57]:
a.size

30

In [58]:
a.reshape((2,3))

ValueError: cannot reshape array of size 30 into shape (2,3)

In [59]:
a.resize((2,3)) #reshape와 다르게 잘라낼 수 있다.

In [60]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [61]:
a.size

6