In [1]:
import numpy as np

In [2]:
a = np.arange(100).reshape((5,-1))

In [3]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [4]:
np.savetxt('a.txt',a,delimiter=',', fmt = '%d')

In [7]:
b = np.loadtxt('a.txt', delimiter = ',', dtype = int)

In [8]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [12]:
daegu_temp = np.loadtxt('daegu_temp.csv', delimiter = ',', skiprows = 8, encoding = 'cp949')

In [13]:
daegu_temp

array([[ 2.0100106e+07,  1.4300000e+02, -5.4000000e+00, -8.4000000e+00,
        -7.0000000e-01],
       [ 2.0100107e+07,  1.4300000e+02, -4.5000000e+00, -7.5000000e+00,
        -4.0000000e-01],
       [ 2.0100108e+07,  1.4300000e+02, -2.8000000e+00, -8.6000000e+00,
         3.2000000e+00],
       ...,
       [ 2.0220204e+07,  1.4300000e+02, -6.0000000e-01, -3.4000000e+00,
         4.2000000e+00],
       [ 2.0220205e+07,  1.4300000e+02, -3.0000000e+00, -6.4000000e+00,
         1.1000000e+00],
       [ 2.0220206e+07,  1.4300000e+02, -1.1000000e+00, -5.0000000e+00,
         3.5000000e+00]])

In [14]:
daegu_temp.shape

(4413, 5)

### 최고온도 구하기.

날짜 지점 평균기온 최저기온 최고기온

In [15]:
daegu_temp[:, 4] 

array([-0.7, -0.4,  3.2, ...,  4.2,  1.1,  3.5])

In [16]:
np.max(daegu_temp[:, 4]) #4번째에서 최고

39.2

In [17]:
np.argmax(daegu_temp[:,4]) #최고온도의 위치

3122

In [18]:
daegu_temp[3122]

array([2.0180727e+07, 1.4300000e+02, 3.2400000e+01, 2.8600000e+01,
       3.9200000e+01])

In [20]:
daegu_temp[np.argmax(daegu_temp[:,4]), 0] #최고온도의 위치의 날짜만

20180727.0

### 최저기온

In [21]:
np.min(daegu_temp[:,3])

-13.9

In [22]:
daegu_temp[np.argmin(daegu_temp[:,3]), 0]

20180127.0

In [ ]:
### 최고기온 top10, 최저기온 top 10

예)
최고기온
1 20180727 39.2도
2
...
10
최저기온
1 20180127 -13.9도
2
...
10