In [5]:
import numpy as np

In [2]:
l = [1,2,1.2,'aaa']

In [5]:
l

[1, 2, 1.2, 'aaa']

In [6]:
type(l)

list

In [7]:
type(l[0])

int

In [8]:
type(l[1])

int

In [9]:
type(l[2])

float

In [10]:
type(l[3])

str

In [11]:
a = np.zeros(5)

In [12]:
a

array([0., 0., 0., 0., 0.])

In [13]:
type(a)

numpy.ndarray

In [14]:
dir()

['In',
 'Out',
 '_',
 '_10',
 '_12',
 '_13',
 '_3',
 '_4',
 '_5',
 '_6',
 '_7',
 '_8',
 '_9',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i11',
 '_i12',
 '_i13',
 '_i14',
 '_i2',
 '_i3',
 '_i4',
 '_i5',
 '_i6',
 '_i7',
 '_i8',
 '_i9',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'a',
 'exit',
 'get_ipython',
 'l',
 'np',
 'quit']

In [15]:
__name__

'__main__'

In [16]:
#if __name__ == "__main__":
#    main()   자기가 만든 main사용

In [17]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [18]:
dir(l)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

# Numpy 배열 생성

In [20]:
a = np.array([1,2,3,4,5])

In [21]:
a

array([1, 2, 3, 4, 5])

In [22]:
a[0]

1

In [23]:
a[4]

5

In [24]:
type(a[0])

numpy.int64

In [25]:
l

[1, 2, 1.2, 'aaa']

In [26]:
b = np.array(l)

In [27]:
b   #문자열의 배열로 되어있음

array(['1', '2', '1.2', 'aaa'], dtype='<U32')

In [29]:
type(b[0])

numpy.str_

In [30]:
a = np.zeros((3,5)) #1로 채워진 배열

In [31]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
a=np.zeros((4,3,6,5))

In [33]:
a

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0

In [34]:
#단위행렬 만드는 2가지 방법
a = np.eye(5)

In [35]:
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
a = np.identity(5) #단순한 것

In [37]:
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
a = np.eye(5, k=1) #1번 인덱스 부터

In [39]:
a

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [40]:
a = np.eye(5, k=2) #2번 인덱스 부터

In [41]:
a

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
a = np.eye(5,k=-1)

In [43]:
a

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [44]:
a = np.ones((3,5)) #1로 채워진 배열

In [45]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [46]:
a = np.full((3,5), 102) #원하는 값으로 채워진 배열

In [47]:
a

array([[102, 102, 102, 102, 102],
       [102, 102, 102, 102, 102],
       [102, 102, 102, 102, 102]])

In [48]:
a = np.full((2,3), False)

In [49]:
a

array([[False, False, False],
       [False, False, False]])

In [50]:
a = np.empty((2,3)) #빈걸(쓰레기값)로 채워진 배열 생성(메모리에 공간만 확보, 최기화x)

In [52]:
a

array([[0.e+000, 1.e-323, 0.e+000],
       [0.e+000, 0.e+000, 0.e+000]])

In [53]:
b = np.ones_like(a) #a의 모양만 가져와 1로채움

In [54]:
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [55]:
a

array([[0.e+000, 1.e-323, 0.e+000],
       [0.e+000, 0.e+000, 0.e+000]])

In [56]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [57]:
list(range(0,1,0.1)) #실수값 불가

TypeError: 'float' object cannot be interpreted as an integer

In [58]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

# 등간격으로 나누기

In [60]:
a = np.linspace(0,100) #0부터 100까지 50(디폴트)개로 나눔

In [61]:
a

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [66]:
a = np.linspace(0,98)

In [67]:
a

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.,
       26., 28., 30., 32., 34., 36., 38., 40., 42., 44., 46., 48., 50.,
       52., 54., 56., 58., 60., 62., 64., 66., 68., 70., 72., 74., 76.,
       78., 80., 82., 84., 86., 88., 90., 92., 94., 96., 98.])

In [68]:
a = np.linspace(0,100,2) #0부터 100까지 2개

In [69]:
a

array([  0., 100.])

In [71]:
a = np.logspace(1,100,20)

In [72]:
a

array([1.00000000e+001, 1.62377674e+006, 2.63665090e+011, 4.28133240e+016,
       6.95192796e+021, 1.12883789e+027, 1.83298071e+032, 2.97635144e+037,
       4.83293024e+042, 7.84759970e+047, 1.27427499e+053, 2.06913808e+058,
       3.35981829e+063, 5.45559478e+068, 8.85866790e+073, 1.43844989e+079,
       2.33572147e+084, 3.79269019e+089, 6.15848211e+094, 1.00000000e+100])

### ndarray 속성

In [75]:
a= np.ones(5)

In [76]:
a

array([1., 1., 1., 1., 1.])

In [77]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [78]:
a.dtype #배열의 데이터 타입

dtype('float64')

In [79]:
a = np.ones(5,dtype=np.int8) #데이터 타입 지정

In [80]:
a

array([1, 1, 1, 1, 1], dtype=int8)

In [81]:
a.dtype

dtype('int8')

In [82]:
a.shape   #배열 모양

(5,)

In [83]:
a = np.ones((3,5))

In [84]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [85]:
a.shape

(3, 5)

In [86]:
a.ndim #배열의 차원확인

2

In [92]:
a = np.zeros((3,2,2,4))

In [93]:
a

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [89]:
a.ndim

4

In [94]:
a.size #원소 갯수

48

In [95]:
a.itemsize #배열안의 아이템 크기(데이터타입의 크기)

8

In [96]:
a.dtype

dtype('float64')

### 파이썬 리스트 vs numpy 배열 속도 비교

In [99]:
%time sum(range(1000000))

CPU times: user 29.2 ms, sys: 597 µs, total: 29.8 ms
Wall time: 29.7 ms


499999500000

In [100]:
%time np.sum(np.arange(1000000)) #더 빠르다

CPU times: user 5.61 ms, sys: 7.23 ms, total: 12.8 ms
Wall time: 13.2 ms


499999500000

# 복사

In [101]:
list_a = [1,2,3,4,5,6,7,8]

In [102]:
list_b = list_a

In [103]:
list_a

[1, 2, 3, 4, 5, 6, 7, 8]

In [104]:
list_b

[1, 2, 3, 4, 5, 6, 7, 8]

In [105]:
list_b[3] = 1004

In [106]:
list_b

[1, 2, 3, 1004, 5, 6, 7, 8]

In [107]:
list_a #a도 바뀜

[1, 2, 3, 1004, 5, 6, 7, 8]

In [108]:
list_a = [1,2,3,4,5,6,7,8]
list_b = list_a.copy()

In [109]:
list_b

[1, 2, 3, 4, 5, 6, 7, 8]

In [110]:
list_a

[1, 2, 3, 4, 5, 6, 7, 8]

In [111]:
list_b[3] = 1004

In [112]:
list_b

[1, 2, 3, 1004, 5, 6, 7, 8]

In [113]:
list_a

[1, 2, 3, 4, 5, 6, 7, 8]

In [114]:
list_c = list_a[1:4]

In [115]:
list_c

[2, 3, 4]

In [116]:
list_c[0] = 2004

In [117]:
list_c

[2004, 3, 4]

In [118]:
list_a

[1, 2, 3, 4, 5, 6, 7, 8]

In [120]:
list_a = [[10,20,30], 1,2,3]
list_d = list_a.copy()

In [121]:
list_d

[[10, 20, 30], 1, 2, 3]

In [122]:
list_d[-1] = 3003

In [123]:
list_d

[[10, 20, 30], 1, 2, 3003]

In [124]:
list_a

[[10, 20, 30], 1, 2, 3]

In [125]:
list_a[0][0]

10

In [126]:
list_a[0][0] = 2002

In [127]:
list_a

[[2002, 20, 30], 1, 2, 3]

In [128]:
list_d #리스트안의 리스트는 값이 바뀜

[[2002, 20, 30], 1, 2, 3003]

In [129]:
import copy
list_d = copy.deepcopy(list_a)

In [130]:
list_a

[[2002, 20, 30], 1, 2, 3]

In [131]:
list_d

[[2002, 20, 30], 1, 2, 3]

In [132]:
list_d[0][0]= 5005

In [133]:
list_d

[[5005, 20, 30], 1, 2, 3]

In [134]:
list_a

[[2002, 20, 30], 1, 2, 3]

In [135]:
a = np.array(np.arange(10))

In [136]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [137]:
b = a #얕은 복사

In [138]:
id(a)

140545315442288

In [139]:
id(b)

140545315442288

In [143]:
c = a[2:4]   #a를 공유. view. (파이썬의 리스트와 다르다.)

In [144]:
c

array([2, 3])

In [145]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
c[0] = 3004

In [147]:
c

array([3004,    3])

In [148]:
a

array([   0,    1, 3004,    3,    4,    5,    6,    7,    8,    9])

In [149]:
d = a.copy() #깊은복사

In [151]:
id(d)

140545314495824

In [152]:
id(a)

140545315442288

In [153]:
c=a.view() #b=a와 다름. c에서 바꾸는 값만 a에 바뀜

### 배열 값을 가져오는 방법

In [155]:
a = np.array(np.arange(1,7))

In [156]:
a

array([1, 2, 3, 4, 5, 6])

In [157]:
a.shape

(6,)

In [158]:
a.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [159]:
a

array([1, 2, 3, 4, 5, 6])

In [160]:
a = a.reshape((2,3))

In [161]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [163]:
a.reshape((3,2)) #아이템 갯수가 맞아야함

array([[1, 2],
       [3, 4],
       [5, 6]])

In [164]:
a.reshape((4,2))

ValueError: cannot reshape array of size 6 into shape (4,2)

In [165]:
a.reshape((3,-1)) #자동으로 열 계산

array([[1, 2],
       [3, 4],
       [5, 6]])

In [166]:
a.reshape((-1,3)) #자동으로 행 계산

array([[1, 2, 3],
       [4, 5, 6]])

In [167]:
a[0]

array([1, 2, 3])

In [168]:
a[0][0]

1

In [169]:
a[0][1:2]

array([2])

In [170]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [171]:
a[1][1]

5

In [172]:
a[1,1] #위와 같음

5

In [173]:
a[0, :2]   #슬라이싱도 가능

array([1, 2])

## boolean indexing

In [174]:
a = np.array(np.arange(1,6))

In [175]:
a

array([1, 2, 3, 4, 5])

In [176]:
a[4]

5

In [177]:
a[[True,False,False,False,False]]

array([1])

In [178]:
a[[True,False,True,True,False]]

array([1, 3, 4])

In [179]:
b = a[[True,False,True,True,False]] #copy

In [180]:
b

array([1, 3, 4])

In [181]:
b[0] = 1004

In [182]:
b

array([1004,    3,    4])

In [183]:
a

array([1, 2, 3, 4, 5])

In [184]:
a[[True,False,True,True,False,True]] #아이템 갯수 같아야 한다.

IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 6

In [185]:
a

array([1, 2, 3, 4, 5])

In [186]:
list_a = [1,2,3,4,5]

In [187]:
list_a > 3 #파이썬 리스트는 불가

TypeError: '>' not supported between instances of 'list' and 'int'

In [188]:
a>3  #element wise 아이템별 연산

array([False, False, False,  True,  True])

In [189]:
a[a>3]

array([4, 5])

In [191]:
list_a + 5

TypeError: can only concatenate list (not "int") to list

In [192]:
a + 5

array([ 6,  7,  8,  9, 10])

In [193]:
a*10

array([10, 20, 30, 40, 50])

In [194]:
a[a>3]*10

array([40, 50])

### a배열 값 중에서 짝수 값만 2배한 새로운 배열b를 만드시오

In [198]:
b = a[a%2==0]*2

In [199]:
b

array([4, 8])

### a배열에서 짝수만 2배하기

In [200]:
a[a%2==0] = a[a%2==0]*2

In [201]:
a

array([1, 4, 3, 8, 5])

In [202]:
a[a<4] = 0

In [203]:
a

array([0, 4, 0, 8, 5])

### fancy indexing

In [204]:
b = np.arange(100).reshape((20,-1))
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [205]:
b[0]

array([0, 1, 2, 3, 4])

In [206]:
b[0][0]

0

In [207]:
b[[2,4,8]] #fancy indexing.  2,4,8행 선택

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [40, 41, 42, 43, 44]])

In [209]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [210]:
b[[2,4,8], [0,3,4]]   #[2][0], [4][3], [8][4]

array([10, 23, 44])

In [211]:
b[:,[0,3,4]]   #모든 행의 0,3,4열 선택

array([[ 0,  3,  4],
       [ 5,  8,  9],
       [10, 13, 14],
       [15, 18, 19],
       [20, 23, 24],
       [25, 28, 29],
       [30, 33, 34],
       [35, 38, 39],
       [40, 43, 44],
       [45, 48, 49],
       [50, 53, 54],
       [55, 58, 59],
       [60, 63, 64],
       [65, 68, 69],
       [70, 73, 74],
       [75, 78, 79],
       [80, 83, 84],
       [85, 88, 89],
       [90, 93, 94],
       [95, 98, 99]])

In [212]:
b[:,:] #전체 = b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [213]:
c = b[:,:]   #view (슬라이싱 부분은 view)

In [214]:
c[0][0]

0

In [215]:
b[0][0]

0

In [216]:
c[0][0] = 1000

In [217]:
c[0][0]

1000

In [218]:
b[0][0]

1000

In [219]:
c = b[[2,4,8], [0,3,4]]   #copy(fancy는 copy)

In [220]:
c

array([10, 23, 44])

In [221]:
c[0] = 5005

In [222]:
c

array([5005,   23,   44])

In [223]:
b[2][0]

10

### vectorized 연산 (벡터화 연산)
elementwise 연산

In [224]:
a = np.array([1,2,3,4,5])

In [225]:
b = np.array([6,7,8,9,10])

In [226]:
a

array([1, 2, 3, 4, 5])

In [227]:
b

array([ 6,  7,  8,  9, 10])

In [228]:
a+b

array([ 7,  9, 11, 13, 15])

In [229]:
a*b

array([ 6, 14, 24, 36, 50])

In [230]:
b>a

array([ True,  True,  True,  True,  True])

In [231]:
c = np.array([2,3,4,5])

In [232]:
a+c #불가. 아이템 갯수 맞춰야됨

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [235]:
c = np.zeros((2,5))

In [236]:
a+c

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

In [237]:
a = np.arange(6).reshape((2,3))
b = np.arange(6,12).reshape((2,3))

In [238]:
a*b

array([[ 0,  7, 16],
       [27, 40, 55]])

In [239]:
a @ b #행렬 곱(행과 열의 갯수 맞춰야됨)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [240]:
b.reshape((3,2))

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [241]:
a @ b.reshape((3,2))

array([[ 28,  31],
       [100, 112]])

In [242]:
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [243]:
b.T #전치행렬 : 행<->열

array([[ 6,  9],
       [ 7, 10],
       [ 8, 11]])

In [244]:
a@b.T

array([[ 23,  32],
       [ 86, 122]])

In [245]:
a*5

array([[ 0,  5, 10],
       [15, 20, 25]])

### Broadcasting

In [246]:
c = np.array([10,20,30])

In [247]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [248]:
c

array([10, 20, 30])

In [249]:
a + c #c를 broadcasting하여 각 행마다 더함

array([[10, 21, 32],
       [13, 24, 35]])

In [251]:
a + np.array([[1],[2]]) #각 열마다 더함

array([[1, 2, 3],
       [5, 6, 7]])

In [252]:
a + np.array([10])

array([[10, 11, 12],
       [13, 14, 15]])

### 축(axis)

In [253]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [258]:
np.sum(a,axis=0) #열 별로(행방향) 따로 계산

array([3, 5, 7])

In [259]:
np.sum(a, axis=1)  #행 별로(열방향) 따로 계산

array([ 3, 12])

In [260]:
np.max(a)

5

In [262]:
np.max(a,axis=0)   #행방향 최댓값

array([3, 4, 5])

In [263]:
np.max(a, axis=1)   #열방향 최댓값

array([2, 5])

### universal function: ufunc
- 벡터화 연산을지원하는 함수들

In [264]:
type(np.max)

function

In [265]:
type(np.add)

numpy.ufunc

In [267]:
np.argmax(a) #a의 최댓값이 있는 인덱스(1차원으로 보고)

5

In [269]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [270]:
np.argmin(a)

0

In [271]:
np.all(a)

False

In [272]:
a.all()   #모든 값이 참인가?(false뿐 아니라 0도 거짓으로 본다.)

False

In [273]:
a.all(axis=0)

array([False,  True,  True])

In [274]:
a.all(axis = 1)

array([False,  True])

In [276]:
a.any()   #하나라도 true이면 true

True

In [277]:
a.any(axis=0)

array([ True,  True,  True])

In [278]:
a.nonzero() #0이 아닌것 위치. 앞의거가 행, 뒤에거가 열

(array([0, 0, 1, 1, 1]), array([1, 2, 0, 1, 2]))

In [279]:
np.where(a>3)   #조건만족하는 것의 위치.

(array([1, 1]), array([1, 2]))

### 난수 생성

In [280]:
np.random.randint(1,6)   #1~5까지 중 랜덤 수

1

In [281]:
np.random.randint(1,7,200)  #200번

array([1, 1, 2, 4, 6, 3, 3, 4, 3, 2, 2, 5, 2, 2, 3, 5, 2, 1, 6, 1, 5, 1,
       6, 3, 3, 3, 2, 4, 6, 1, 2, 1, 4, 1, 6, 3, 3, 6, 4, 5, 4, 5, 4, 5,
       5, 6, 3, 6, 3, 3, 5, 3, 1, 4, 3, 4, 5, 2, 3, 6, 1, 3, 3, 1, 5, 3,
       4, 3, 1, 6, 5, 3, 2, 1, 5, 3, 5, 5, 2, 5, 3, 6, 6, 5, 5, 4, 3, 3,
       6, 1, 3, 3, 1, 3, 1, 4, 5, 2, 5, 4, 1, 1, 6, 6, 1, 6, 5, 4, 2, 2,
       1, 4, 2, 5, 1, 4, 6, 1, 5, 5, 5, 4, 2, 5, 1, 5, 5, 4, 1, 1, 5, 3,
       1, 6, 3, 5, 1, 1, 4, 3, 6, 3, 2, 4, 6, 5, 1, 5, 5, 5, 6, 2, 2, 6,
       2, 5, 2, 6, 6, 6, 2, 2, 5, 5, 1, 1, 1, 1, 5, 3, 3, 2, 4, 1, 3, 5,
       4, 4, 5, 5, 6, 2, 2, 1, 2, 3, 4, 2, 2, 4, 4, 2, 2, 1, 6, 1, 3, 1,
       6, 2])

In [282]:
np.random.rand(5)  #0~1까지 실수 5개

array([0.06232916, 0.75819631, 0.82849655, 0.38786127, 0.77918818])

In [285]:
np.random.randn(100)   #표준 정규분포값에따라

array([-0.35636376,  1.02883711, -1.68663677, -0.39919432, -0.18303097,
       -0.05247963,  0.32508553,  1.32173207, -0.26948616, -1.87048924,
        0.13822847, -0.14280589,  0.36891581,  1.16441023, -1.96434168,
        1.18179   ,  0.75269817,  2.77172783, -0.59407334, -0.30615226,
        1.65361652, -1.5288839 , -0.14622637, -0.42417809,  0.50210153,
        1.34558488,  0.78668009,  0.1572916 ,  1.01702542,  0.31090638,
       -0.08290807,  0.6604039 ,  1.30214262,  0.17210247, -0.62445484,
       -0.1700596 , -0.08443013, -0.57442923,  0.93512098, -0.28423373,
        0.20547679, -0.85241629,  0.072424  , -1.08394103,  0.95634302,
       -0.07186205,  0.78584453,  0.57406103,  0.50011188, -1.22284446,
        0.17570489,  1.1571372 ,  0.75163242, -0.80270832,  0.34075592,
        1.41078492,  1.68651249, -0.33767779,  0.1726212 , -0.58232387,
        1.99391906,  0.11972971, -0.41587901, -0.06469002,  0.10656392,
       -0.3558444 ,  2.26448017, -0.26334077,  0.2649064 , -0.30

In [286]:
np.random.randint(1,46,6)

array([11, 19, 22, 33, 14, 16])

### resize

In [287]:
a.size

6

In [288]:
a = np.arange(24)

In [289]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [290]:
a.size

24

In [291]:
a.resize((2,2))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [292]:
a.resize((2,2), refcheck=False)   #a가 바뀜

In [293]:
a

array([[0, 1],
       [2, 3]])

In [294]:
a = np.arange(24)

In [295]:
np.resize(a, (2,3,8))

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]],

       [[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]]])

In [296]:
np.resize(a,35)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10])

In [297]:
a = np.random.randint(1,46,100)

In [298]:
a

array([39, 39, 22, 13,  5, 19, 29,  7, 17, 39, 20,  5,  2, 19, 43, 22, 26,
        4, 18, 16, 22,  9, 42,  3,  1, 22, 43, 14, 43, 41, 16, 45, 30, 19,
        2,  6, 35, 26, 45, 26, 30, 12, 33,  3, 21,  7, 11, 29, 43,  9,  7,
        8,  3, 30, 15,  1, 23, 22, 44, 28, 34, 28, 32,  1, 22, 41, 42, 14,
       34, 41, 40,  5, 17, 34, 19, 43, 15, 17,  4,  4, 23, 20, 37, 24,  1,
        4, 40, 33, 30, 18, 14, 13, 29,  1, 35, 23, 20, 39, 37, 35])

In [299]:
a=a.reshape((10,-1))

In [300]:
a

array([[39, 39, 22, 13,  5, 19, 29,  7, 17, 39],
       [20,  5,  2, 19, 43, 22, 26,  4, 18, 16],
       [22,  9, 42,  3,  1, 22, 43, 14, 43, 41],
       [16, 45, 30, 19,  2,  6, 35, 26, 45, 26],
       [30, 12, 33,  3, 21,  7, 11, 29, 43,  9],
       [ 7,  8,  3, 30, 15,  1, 23, 22, 44, 28],
       [34, 28, 32,  1, 22, 41, 42, 14, 34, 41],
       [40,  5, 17, 34, 19, 43, 15, 17,  4,  4],
       [23, 20, 37, 24,  1,  4, 40, 33, 30, 18],
       [14, 13, 29,  1, 35, 23, 20, 39, 37, 35]])

### 배열을파일로

In [302]:
np.savetxt('rand1to45.csv', a, delimiter=',',fmt='%d')

### 파일로부터 데이터를 읽어 배열 만들기

In [307]:
b = np.loadtxt('rand1to45.csv', delimiter=',')

In [308]:
b

array([[39., 39., 22., 13.,  5., 19., 29.,  7., 17., 39.],
       [20.,  5.,  2., 19., 43., 22., 26.,  4., 18., 16.],
       [22.,  9., 42.,  3.,  1., 22., 43., 14., 43., 41.],
       [16., 45., 30., 19.,  2.,  6., 35., 26., 45., 26.],
       [30., 12., 33.,  3., 21.,  7., 11., 29., 43.,  9.],
       [ 7.,  8.,  3., 30., 15.,  1., 23., 22., 44., 28.],
       [34., 28., 32.,  1., 22., 41., 42., 14., 34., 41.],
       [40.,  5., 17., 34., 19., 43., 15., 17.,  4.,  4.],
       [23., 20., 37., 24.,  1.,  4., 40., 33., 30., 18.],
       [14., 13., 29.,  1., 35., 23., 20., 39., 37., 35.]])

In [309]:
b.dtype

dtype('float64')

In [313]:
c = np.loadtxt('rand1to45.csv', delimiter=',', dtype=np.int64)

In [314]:
c

array([[39, 39, 22, 13,  5, 19, 29,  7, 17, 39],
       [20,  5,  2, 19, 43, 22, 26,  4, 18, 16],
       [22,  9, 42,  3,  1, 22, 43, 14, 43, 41],
       [16, 45, 30, 19,  2,  6, 35, 26, 45, 26],
       [30, 12, 33,  3, 21,  7, 11, 29, 43,  9],
       [ 7,  8,  3, 30, 15,  1, 23, 22, 44, 28],
       [34, 28, 32,  1, 22, 41, 42, 14, 34, 41],
       [40,  5, 17, 34, 19, 43, 15, 17,  4,  4],
       [23, 20, 37, 24,  1,  4, 40, 33, 30, 18],
       [14, 13, 29,  1, 35, 23, 20, 39, 37, 35]])

In [315]:
b.astype(np.int64)

array([[39, 39, 22, 13,  5, 19, 29,  7, 17, 39],
       [20,  5,  2, 19, 43, 22, 26,  4, 18, 16],
       [22,  9, 42,  3,  1, 22, 43, 14, 43, 41],
       [16, 45, 30, 19,  2,  6, 35, 26, 45, 26],
       [30, 12, 33,  3, 21,  7, 11, 29, 43,  9],
       [ 7,  8,  3, 30, 15,  1, 23, 22, 44, 28],
       [34, 28, 32,  1, 22, 41, 42, 14, 34, 41],
       [40,  5, 17, 34, 19, 43, 15, 17,  4,  4],
       [23, 20, 37, 24,  1,  4, 40, 33, 30, 18],
       [14, 13, 29,  1, 35, 23, 20, 39, 37, 35]])

In [319]:
b = b.astype(np.int64)

In [320]:
b

array([[39, 39, 22, 13,  5, 19, 29,  7, 17, 39],
       [20,  5,  2, 19, 43, 22, 26,  4, 18, 16],
       [22,  9, 42,  3,  1, 22, 43, 14, 43, 41],
       [16, 45, 30, 19,  2,  6, 35, 26, 45, 26],
       [30, 12, 33,  3, 21,  7, 11, 29, 43,  9],
       [ 7,  8,  3, 30, 15,  1, 23, 22, 44, 28],
       [34, 28, 32,  1, 22, 41, 42, 14, 34, 41],
       [40,  5, 17, 34, 19, 43, 15, 17,  4,  4],
       [23, 20, 37, 24,  1,  4, 40, 33, 30, 18],
       [14, 13, 29,  1, 35, 23, 20, 39, 37, 35]])

In [323]:
# 0~9까지 값을 가진 배열a를 만들어 보세요.
a = np.arange(10)

In [324]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [325]:
# a배열에서 홀수 값만 선택해 보시오.
a[a%2!=0]

array([1, 3, 5, 7, 9])

In [326]:
# a배열의 홀수 값을 모두 -1로 변경
a[a%2 == 1] = -1

In [327]:
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [330]:
# a배열의 모양을 (2,5)의 형태로 바꿔서 b에 저장
b = a.reshape((2,5))

In [331]:
b

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

In [332]:
# b배열의 1번 열과 3번 열의 위치를 바꿔서 c에 저장하시오
c = b[:,[0,3,2,1,4]]

In [333]:
c

array([[ 0, -1,  2, -1,  4],
       [-1,  8, -1,  6, -1]])

In [334]:
# b배열의 0행과 1번행을 바꾸어 d에 저장
d = b[[1,0],:]
d

array([[-1,  6, -1,  8, -1],
       [ 0, -1,  2, -1,  4]])

In [6]:
daegu = np.loadtxt('daegu.csv', delimiter=',', dtype='str')

In [7]:
daegu_date = daegu[:,[0]]
daeguDate = np.empty((len(daegu_date),1))
count = 0
for i in daegu_date:
    q = i[0].split('/')
    daeguDate[count] = q[2]+q[0]+q[1]
    count+=1
    
daeguDate

array([[20170101.],
       [20170102.],
       [20170103.],
       ...,
       [20220722.],
       [20220723.],
       [20220724.]])

In [8]:
daegu.shape

(2031, 5)

In [9]:
#데이터 모양
#날짜0, 지점1, 평균2, 최저3,최고4

In [10]:
# 최근 5년간 최고기온을 구하시오
daegu_temp = daegu[:,[1,2,3,4]]
daegu_temp = daegu_temp.astype(np.float64)
np.max(daegu_temp, axis=0)[3]

39.2

In [11]:
np.max(daegu_temp[:,3])

39.2

In [12]:
daeguTemp = np.concatenate([daeguDate, daegu_temp], axis=1)
daeguTemp

array([[ 2.0170101e+07,  1.4300000e+02,  3.4000000e+00, -2.0000000e+00,
         1.0000000e+01],
       [ 2.0170102e+07,  1.4300000e+02,  5.3000000e+00, -4.0000000e-01,
         1.2300000e+01],
       [ 2.0170103e+07,  1.4300000e+02,  5.2000000e+00,  9.0000000e-01,
         1.0900000e+01],
       ...,
       [ 2.0220722e+07,  1.4300000e+02,  2.5800000e+01,  2.2600000e+01,
         2.9700000e+01],
       [ 2.0220723e+07,  1.4300000e+02,  2.4900000e+01,  2.2100000e+01,
         2.8600000e+01],
       [ 2.0220724e+07,  1.4300000e+02,  2.7400000e+01,  2.2300000e+01,
         3.2000000e+01]])

In [13]:
# 최저기온
np.min(daegu_temp[:,2])

-13.9

In [14]:
np.argmax(daegu_temp[:,3])

572

In [15]:
daegu_date[572][0]

'07/27/2018'

In [16]:
daeguTemp[572][0]

20180727.0

In [17]:
daeguTemp[np.argmin(daeguTemp[:,3])][0].astype(np.int64)

20180127

In [39]:
# 최저기온, 최고기온 top10
def getTempTop(tData, n=10):
    highTempTop = {}
    lowTempTop = {}
    for i in range(n):
        maxTempIndex = np.argmax(tData[:,4])
        highestTemp = tData[maxTempIndex,4]
        highestTempDate = tData[maxTempIndex,0].astype(np.int64)
        highTempTop[highestTempDate] = highestTemp
        
        minTempIndex = np.argmin(tData[:,3])
        lowestTemp = tData[minTempIndex,3]
        lowestTempDate = tData[minTempIndex][0].astype(np.int64)
        lowTempTop[lowestTempDate] = lowestTemp
        
        if maxTempIndex == minTempIndex:
            tData = np.delete(tData, minTempIndex, axis=0)
        elif maxTempIndex > minTempIndex:
            tData = np.delete(tData, maxTempIndex, axis=0)
            tData = np.delete(tData, minTempIndex, axis=0)
        else:
            tData = np.delete(tData, minTempIndex, axis=0)
            tData = np.delete(tData, maxTempIndex, axis=0)
            
    return highTempTop, lowTempTop

In [40]:
htop10, ltop10 = getTempTop(daeguTemp)

In [26]:
htop10

{20180727: 39.2,
 20180804: 38.7,
 20180724: 38.6,
 20180720: 38.5,
 20170722: 38.4,
 20180723: 38.0,
 20180726: 38.0,
 20180803: 37.8,
 20180801: 37.5,
 20170713: 37.2}

In [41]:
ltop10

{20180127: -13.9,
 20210108: -13.6,
 20180126: -13.0,
 20180125: -12.4,
 20210107: -12.4,
 20180124: -12.3,
 20210109: -11.4,
 20180206: -10.9,
 20180207: -10.9,
 20210110: -10.8}

In [ ]:
#np.delete
#a=np.delete(a,100,axis=0)  a배열의 100번 인덱스 지우기

In [397]:
myList = [x*2for x in range(10)]
print(myList)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
